#!/usr/bin/env python3
"""Inline and gzip the Vite build into a flash-resident C++ header."""

from __future__ import annotations

import gzip
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
DIST = ROOT / "web" / "dist"
OUTPUT = ROOT / "src" / "WebAssets.generated.h"


def build_document() -> bytes:
    document = (DIST / "index.html").read_text()
    script = (DIST / "assets" / "app.js").read_text().replace("</script", "<\\/script")
    styles_path = DIST / "assets" / "index.css"
    styles = styles_path.read_text() if styles_path.exists() else ""
    document = re.sub(
        r'<script[^>]+src="/assets/app\.js"[^>]*></script>',
        lambda _: f"<script type=module>{script}</script>",
        document,
    )
    document = re.sub(
        r'<link[^>]+href="/assets/index\.css"[^>]*>',
        lambda _: f"<style>{styles}</style>",
        document,
    )
    document = re.sub(r">\s+<", "><", document).strip()
    return document.encode()


def byte_rows(payload: bytes) -> str:
    values = [f"0x{value:02x}" for value in payload]
    return "\n".join("  " + ", ".join(values[index:index + 16]) + "," for index in range(0, len(values), 16))


def main() -> None:
    compressed = gzip.compress(build_document(), compresslevel=9, mtime=0)
    OUTPUT.write_text(
        "#pragma once\n\n"
        "#include <Arduino.h>\n\n"
        "// Generated by firmware/scripts/embed_web.py. Do not edit.\n"
        "const uint8_t kWebAppGzip[] PROGMEM = {\n"
        f"{byte_rows(compressed)}\n"
        "};\n"
        f"constexpr size_t kWebAppGzipSize = {len(compressed)};\n"
    )
    print(f"embedded web ui: {len(compressed)} bytes gzip")


if __name__ == "__main__":
    main()
