"""Build tiny weather glyphs from geometric primitives, without runtime RAM."""
from pathlib import Path
from PIL import Image, ImageDraw

target = Path(__file__).resolve().parents[1] / "src/fonts/WeatherGlyphs.h"
output = ['#pragma once', '// Generated by scripts/weather_glyphs.py; original geometric icons.']
for size in (24, 48, 96):
    bitmaps, glyphs = [], []
    for code in range(16):
        image = Image.new('1', (size, size))
        d = ImageDraw.Draw(image)
        scale = size / 24

        def box(coords):
            return tuple(round(x * scale) for x in coords)

        def circle(coords, fill=1):
            d.ellipse(box(coords), fill=fill)

        def line(points, width=1):
            d.line([box(point) for point in points], fill=1, width=max(1, round(width * scale)))

        def cloud():
            circle((3, 8, 12, 17)); circle((8, 5, 19, 17)); circle((15, 10, 23, 17))
            d.rectangle(box((7, 12, 19, 17)), fill=1)

        def sun():
            circle((7, 7, 17, 17))
            for points in [[(12, 1), (12, 4)], [(12, 20), (12, 23)], [(1, 12), (4, 12)],
                           [(20, 12), (23, 12)], [(3, 3), (5, 5)], [(19, 19), (21, 21)],
                           [(3, 21), (5, 19)], [(19, 5), (21, 3)]]:
                line(points)

        if code == 0:
            circle((3, 2, 22, 22)); circle((9, 0, 24, 17), 0)
        elif code == 11:
            sun()
        elif code in (12, 13, 2):
            if code == 13: cloud()
            for y in (8, 12, 16, 20): line([(3, y), (20 if y % 8 else 15, y)])
        elif code in (14, 15):
            d.polygon([box(p) for p in [(12, 2), (23, 22), (1, 22)]], outline=1, width=max(1, round(scale)))
            line([(12, 8), (12, 15)], 2); circle((11, 18, 13, 20))
        else:
            if code == 6:
                circle((1, 1, 13, 13)); circle((2, 2, 12, 12), 0)
            cloud()
            if code in (4, 5):
                d.polygon([box(p) for p in [(12, 14), (17, 14), (13, 19), (15, 19), (9, 24), (11, 18), (9, 18)]], fill=1)
            if code in (7, 8, 5, 10):
                for x in (5, 11, 18): line([(x, 19), (x-1, 22)], 1 if code != 7 else 2)
            if code in (3, 9, 10):
                for x in (5, 12, 20):
                    if code == 3: circle((x-1, 20, x+1, 22))
                    else:
                        line([(x, 19), (x, 23)]); line([(x-2, 21), (x+2, 21)])
        offset = len(bitmaps)
        pixels = list(image.getdata())
        for start in range(0, len(pixels), 8):
            bitmaps.append(sum(bool(value) << (7-index) for index, value in enumerate(pixels[start:start+8])))
        glyphs.append(f'{{{offset},{size},{size},{size},0,{-size+1}}}')
    output.append(f'const uint8_t Weather{size}Bitmaps[] PROGMEM = {{')
    output.extend(','.join(f'0x{b:02x}' for b in bitmaps[i:i+24])+',' for i in range(0,len(bitmaps),24))
    output.append('};')
    output.append(f'const GFXglyph Weather{size}Glyphs[] PROGMEM = {{'+','.join(glyphs)+'};')
    output.append(f'const GFXfont Weather{size} PROGMEM = {{(uint8_t*)Weather{size}Bitmaps,(GFXglyph*)Weather{size}Glyphs,65,80,{size}}};')
target.write_text('\n'.join(output)+'\n')
