import { css, html, LitElement, nothing } from "lit";
import { customElement, property, state } from "lit/decorators.js";
import type { CardConfig, Dashboard, Display, DisplayCard, Hass, Style } from "./types";
import { newCard, newDashboard, newPage, newRow } from "./types";
import "./preview";

@customElement("mini-display-dashboard-card-editor")
export class MiniDisplayEditor extends LitElement {
  @property({ attribute: false }) hass?: Hass;
  @state() private config: CardConfig = { config_entry_id: "" };
  @state() private dashboard?: Dashboard;
  @state() private displays: Display[] = [];
  @state() private pageIndex = 0;
  @state() private selected?: { row: number; card: number };
  @state() private message = "";

  static styles = css`
    :host{display:block}.layout{display:grid;grid-template-columns:minmax(320px,1fr) 270px;gap:16px}.editor{display:grid;gap:12px}.preview{position:sticky;top:8px;height:max-content}.toolbar,.tabs,.row-head,.card-head{display:flex;align-items:center;justify-content:space-between;gap:6px}.tabs{justify-content:flex-start;overflow:auto}.panel,.row-panel,.settings{padding:12px;border:1px solid var(--divider-color);border-radius:10px;display:grid;gap:10px}.cards{display:grid;gap:8px}.tile{min-width:0;padding:10px;border:1px solid var(--divider-color);border-radius:8px;background:color-mix(in srgb,var(--card-background-color),var(--primary-color) 5%);cursor:pointer}.tile[selected]{outline:2px solid var(--primary-color)}.tile strong,.tile small{display:block;overflow:hidden;text-overflow:ellipsis}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}label{display:grid;gap:4px;font-size:12px}input,select,button{box-sizing:border-box;min-height:36px;padding:6px 9px;color:var(--primary-text-color);background:var(--card-background-color);border:1px solid var(--divider-color);border-radius:6px}button{cursor:pointer}.primary{background:var(--primary-color);color:var(--text-primary-color)}.danger{color:var(--error-color)}ha-entity-picker{display:block}.message{color:var(--secondary-text-color)}
    @media(max-width:800px){.layout{grid-template-columns:1fr}.preview{position:static;order:-1}.grid{grid-template-columns:1fr}}
  `;

  setConfig(config: CardConfig) { this.config = config; void this.load(); }
  private changed() { this.dashboard = structuredClone(this.dashboard); this.message = "Unsaved changes"; }
  private async load() {
    if (!this.hass) return;
    this.displays = await this.hass.callWS<Display[]>({type:"mini_display/displays"});
    if (this.config.config_entry_id) this.dashboard = await this.hass.callWS<Dashboard | null>({type:"mini_display/dashboard/get",config_entry_id:this.config.config_entry_id}) ?? newDashboard();
  }
  updated(changed: Map<string, unknown>) { if (changed.has("hass") && !this.dashboard) void this.load(); }
  private emitConfig(id: string) { this.config = {...this.config,config_entry_id:id}; this.dispatchEvent(new CustomEvent("config-changed",{bubbles:true,composed:true,detail:{config:this.config}})); this.dashboard=undefined; void this.load(); }
  private async apply() { if (!this.hass || !this.dashboard) return; await this.hass.callWS({type:"mini_display/dashboard/set",config_entry_id:this.config.config_entry_id,dashboard:this.dashboard}); this.message="Saved and sent to display"; }
  private field(label: string, value: unknown, update: (value: string) => void, type="text") { return html`<label>${label}<input type=${type} .value=${String(value ?? "")} @change=${(e:Event)=>update((e.target as HTMLInputElement).value)}></label>`; }
  private select(label:string,value:string,values:string[],update:(value:string)=>void){return html`<label>${label}<select .value=${value} @change=${(e:Event)=>update((e.target as HTMLSelectElement).value)}>${values.map(v=>html`<option value=${v}>${v}</option>`)}</select></label>`}
  private entity(card: DisplayCard) { return html`<label>Entity<ha-entity-picker .hass=${this.hass} .value=${card.source ?? ""} allow-custom-entity @value-changed=${(e:CustomEvent)=>{card.source=e.detail.value;this.changed()}}></ha-entity-picker></label>`; }
  private styleEditor(card:DisplayCard){const style=card.style ??= {};const value=card.valueStyle ??= {};return html`<details><summary>Colors and font</summary><div class="grid">${this.field("Background",style.background,v=>{style.background=v;this.changed()})}${this.field("Foreground",style.foreground,v=>{style.foreground=v;this.changed()})}${this.field("Accent",style.accent,v=>{style.accent=v;this.changed()})}${this.select("Font",value.fontFamily??"sans",["sans","sans-bold","mono","serif"],v=>{value.fontFamily=v as Style["fontFamily"];this.changed()})}${this.select("Font size",value.fontSize??"auto",["auto","small","medium","large","xlarge"],v=>{value.fontSize=v as Style["fontSize"];this.changed()})}</div></details>`}
  private cardSettings(card:DisplayCard,row:number,index:number){return html`<div class="settings"><div class="card-head"><b>Card ${index+1} settings</b><button class="danger" @click=${()=>{const cards=this.dashboard!.pages[this.pageIndex].rows[row].cards;if(cards.length>1){cards.splice(index,1);this.selected=undefined;this.changed()}}}>Delete</button></div><div class="grid">${this.select("Type",card.type,["number","text","clock","status"],v=>{Object.keys(card).forEach(k=>delete (card as unknown as Record<string,unknown>)[k]);Object.assign(card,newCard(v as DisplayCard["type"]));this.changed()})}${this.field("Title",card.title,v=>{card.title=v;this.changed()})}${["number","status","text"].includes(card.type)?this.entity(card):nothing}${card.type==="number"?html`${this.field("Unit",card.unit,v=>{card.unit=v;this.changed()})}${this.field("Minimum",card.minimum,v=>{card.minimum=Number(v);this.changed()},"number")}${this.field("Maximum",card.maximum,v=>{card.maximum=Number(v);this.changed()},"number")}${this.select("Progress",card.progress??"none",["none","bar","ring"],v=>{card.progress=v as DisplayCard["progress"];this.changed()})}`:nothing}${card.type==="text"?this.field("Static text",card.text,v=>{card.text=v;this.changed()}):nothing}${card.type==="status"?html`${this.field("On text",card.onText,v=>{card.onText=v;this.changed()})}${this.field("Off text",card.offText,v=>{card.offText=v;this.changed()})}`:nothing}</div>${this.styleEditor(card)}</div>`}

  render(){const page=this.dashboard?.pages[this.pageIndex];return html`<div class="layout"><div class="editor"><label>Display<select .value=${this.config.config_entry_id} @change=${(e:Event)=>this.emitConfig((e.target as HTMLSelectElement).value)}><option value="">Select display</option>${this.displays.map(d=>html`<option value=${d.config_entry_id}>${d.title}${d.available?"":" (offline)"}</option>`)}</select></label>${page?html`<div class="tabs">${this.dashboard!.pages.map((p,i)=>html`<button class=${i===this.pageIndex?"primary":""} @click=${()=>{this.pageIndex=i;this.selected=undefined}}>${p.title||p.id}</button>`)}<button @click=${()=>{this.dashboard!.pages.push(newPage(this.dashboard!.pages.length+1));this.pageIndex=this.dashboard!.pages.length-1;this.changed()}}>+ Page</button></div><div class="panel"><div class="toolbar"><b>Page</b><button class="danger" @click=${()=>{if(this.dashboard!.pages.length>1){this.dashboard!.pages.splice(this.pageIndex,1);this.pageIndex=Math.max(0,this.pageIndex-1);this.changed()}}}>Delete</button></div><div class="grid">${this.field("ID",page.id,v=>{page.id=v;this.changed()})}${this.field("Title",page.title,v=>{page.title=v;this.changed()})}${this.field("Duration seconds",page.durationSeconds,v=>{page.durationSeconds=Number(v);this.changed()},"number")}</div></div>${page.rows.map((row,ri)=>html`<div class="row-panel"><div class="row-head"><b>Row ${ri+1}</b><span><button class="danger" @click=${()=>{if(page.rows.length>1){page.rows.splice(ri,1);this.changed()}}}>Delete</button></span></div><div class="grid">${this.field("Row title",row.title,v=>{row.title=v;this.changed()})}${this.field("Height weight",row.weight,v=>{row.weight=Number(v);this.changed()},"number")}</div><div class="cards" style=${`grid-template-columns:repeat(${row.cards.length},minmax(0,1fr))`}>${row.cards.map((card,ci)=>html`<div class="tile" ?selected=${this.selected?.row===ri&&this.selected?.card===ci} @click=${()=>this.selected={row:ri,card:ci}}><strong>${card.title||card.type}</strong><small>${card.source||card.text||card.type}</small></div>`)}</div>${this.selected?.row===ri?this.cardSettings(row.cards[this.selected.card],ri,this.selected.card):nothing}${row.cards.length<3?html`<button @click=${()=>{row.cards.push(newCard());this.selected={row:ri,card:row.cards.length-1};this.changed()}}>+ Card</button>`:nothing}</div>`)}${page.rows.length<6?html`<button @click=${()=>{page.rows.push(newRow());this.changed()}}>+ Row</button>`:nothing}<button class="primary" @click=${this.apply}>Apply to display</button><div class="message">${this.message}</div>`:nothing}</div><aside class="preview"><mini-display-preview .dashboard=${this.dashboard} .hass=${this.hass} .page=${this.pageIndex}></mini-display-preview></aside></div>`}
}
