import { css, html, LitElement, nothing } from "lit";
import { customElement, property, state } from "lit/decorators.js";
import type { CardConfig, Dashboard, Display, DisplayCard, DisplayRow, Hass, Style } from "./types";
import { newCard, newDashboard, newPage, newRow } from "./types";

@customElement("mini-display-dashboard-card-editor")
export class MiniDisplayEditor extends LitElement {
  @property({ attribute: false }) hass?: Hass;
  @state() private config: CardConfig = { config_entry_id: "" };
  @state() private dashboard?: Dashboard;
  @state() private displays: Display[] = [];
  @state() private pageIndex = 0;
  @state() private selected?: { row: number; card: number };
  @state() private syncState: "idle" | "syncing" | "success" | "error" = "idle";
  @state() private syncMessage = "";
  private syncTimer?: number;

  static styles = css`
    :host{display:block;color:var(--primary-text-color)}*{box-sizing:border-box}.editor{display:grid;gap:16px;min-width:0}.topbar,.row-head,.card-head,.sync{display:flex;align-items:center;justify-content:space-between;gap:8px}.sync{justify-content:flex-start;min-height:20px;font-size:12px;color:var(--secondary-text-color)}.sync i{width:8px;height:8px;border-radius:50%;background:var(--disabled-text-color)}.sync.syncing i{background:var(--warning-color)}.sync.success i{background:var(--success-color)}.sync.error{color:var(--error-color)}.sync.error i{background:var(--error-color)}.tabs,.card-tabs{display:flex;gap:8px;overflow:auto;padding:2px}.tabs button,.card-tabs button{white-space:nowrap}.tabs button.active,.card-tabs button.active{background:var(--primary-color);color:var(--text-primary-color);border-color:var(--primary-color)}.page-settings,.row-panel,.card-settings{padding:12px;border:1px solid var(--divider-color);border-radius:12px}.page-settings[open],.card-settings{display:grid;gap:12px}.page-settings>summary{font-weight:600}.rows{display:grid;gap:12px}.row-panel{display:grid;gap:12px;background:color-mix(in srgb,var(--card-background-color),var(--primary-color) 2%)}.row-title{display:flex;align-items:center;gap:8px}.row-title small{color:var(--secondary-text-color)}.card-settings{border-color:var(--primary-color);background:var(--card-background-color)}.hint{grid-column:1/-1;margin:0;color:var(--secondary-text-color);font-size:12px;line-height:1.5}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.check{display:flex;align-items:center;gap:8px;color:var(--primary-text-color)}.check input{min-height:auto;width:18px;height:18px}label{display:grid;gap:5px;font-size:12px;color:var(--secondary-text-color)}input,select,button{min-height:40px;padding:8px 11px;color:var(--primary-text-color);background:var(--card-background-color);border:1px solid var(--divider-color);border-radius:8px;font:inherit}input:focus-visible,select:focus-visible,button:focus-visible,summary:focus-visible{outline:2px solid var(--primary-color);outline-offset:2px}button{cursor:pointer}button.add{width:100%;border-style:dashed;color:var(--primary-color)}button:disabled{opacity:.45;cursor:default}.menu{position:relative}.menu>summary{list-style:none;display:grid;place-items:center;width:40px;height:40px;border-radius:50%;cursor:pointer}.menu>summary::-webkit-details-marker{display:none}.menu>summary:hover{background:var(--secondary-background-color)}.menu-popover{position:absolute;right:0;z-index:5;width:160px;padding:6px;background:var(--card-background-color);border:1px solid var(--divider-color);border-radius:10px;box-shadow:var(--ha-card-box-shadow);display:grid}.menu-popover button{border:0;text-align:left}.menu-popover .danger{color:var(--error-color)}details>summary{cursor:pointer}.style{padding-top:4px}ha-form{display:block}
    @media(max-width:600px){.grid{grid-template-columns:1fr}}@media(prefers-reduced-motion:reduce){.tile{transition:none}}
  `;

  setConfig(config: CardConfig) { this.config = config; void this.load(); }
  updated(changed: Map<string, unknown>) { if (changed.has("hass") && !this.dashboard) void this.load(); }
  disconnectedCallback() {
    window.clearTimeout(this.syncTimer);
    if (this.syncState === "syncing") void this.sync();
    super.disconnectedCallback();
  }
  private async load() { if (!this.hass) return; this.displays = await this.hass.callWS<Display[]>({ type: "mini_display/displays" }); if (this.config.config_entry_id) { this.dashboard = await this.hass.callWS<Dashboard | null>({ type: "mini_display/dashboard/get", config_entry_id: this.config.config_entry_id }) ?? newDashboard(); this.selected = { row: 0, card: 0 }; } }
  private selectDisplay(id: string) { this.config = { ...this.config, config_entry_id: id }; this.dispatchEvent(new CustomEvent("config-changed", { bubbles: true, composed: true, detail: { config: this.config } })); this.dashboard = undefined; this.pageIndex = 0; this.selected = undefined; void this.load(); }
  private changed() { this.dashboard = structuredClone(this.dashboard); this.syncState = "syncing"; this.syncMessage = "Synchronizing"; window.clearTimeout(this.syncTimer); this.syncTimer = window.setTimeout(() => void this.sync(), 500); }
  private async sync() { if (!this.hass || !this.dashboard || !this.config.config_entry_id) return; try { await this.hass.callWS({ type: "mini_display/dashboard/set", config_entry_id: this.config.config_entry_id, dashboard: this.dashboard, page_id: this.dashboard.pages[this.pageIndex].id }); this.syncState = "success"; this.syncMessage = "Synchronized"; window.dispatchEvent(new CustomEvent("mini-display-dashboard-updated", { detail: { configEntryId: this.config.config_entry_id } })); } catch (error) { this.syncState = "error"; this.syncMessage = String(error); } }
  private async showPage(index: number) { this.pageIndex = index; this.selected = { row: 0, card: 0 }; if (!this.hass || !this.config.config_entry_id || !this.dashboard) return; try { await this.hass.callWS({ type: "mini_display/page/show", config_entry_id: this.config.config_entry_id, page_id: this.dashboard.pages[index].id }); } catch (error) { this.syncState = "error"; this.syncMessage = String(error); } }
  private field(label: string, value: unknown, update: (value: string) => void, type = "text") { return html`<label>${label}<input type=${type} .value=${String(value ?? "")} @input=${(event: Event) => update((event.target as HTMLInputElement).value)}></label>`; }
  private select(label: string, value: string, values: string[], update: (value: string) => void) { return html`<label>${label}<select @change=${(event: Event) => update((event.target as HTMLSelectElement).value)}>${values.map(item => html`<option value=${item} ?selected=${item === value}>${item}</option>`)}</select></label>`; }
  private checkbox(label: string, value: boolean, update: (value: boolean) => void) { return html`<label class="check"><input type="checkbox" .checked=${value} @change=${(event: Event) => update((event.target as HTMLInputElement).checked)}>${label}</label>`; }
  private entity(card: DisplayCard) {
    const domains: Record<DisplayCard["type"], string[]> = {
      number: ["sensor", "number", "input_number", "counter"],
      status: ["binary_sensor", "switch", "input_boolean", "lock", "cover", "person", "device_tracker"],
      text: ["sensor", "text", "input_text", "select", "input_select"],
      clock: [],
    };
    return html`<ha-form .hass=${this.hass} .data=${{ entity: card.source ?? "" }} .schema=${[{ name: "entity", required: card.type !== "text", selector: { entity: { domain: domains[card.type] } } }]} .computeLabel=${() => card.type === "number" ? "Numeric entity" : card.type === "status" ? "State entity" : "Text entity (optional)"} @value-changed=${(event: CustomEvent) => { card.source = event.detail.value.entity; this.changed(); }}></ha-form>`;
  }
  private menu(items: unknown) { return html`<details class="menu"><summary aria-label="More actions"><ha-icon icon="mdi:dots-vertical"></ha-icon></summary><div class="menu-popover">${items}</div></details>`; }
  private styleEditor(card: DisplayCard) { const style = card.style ??= {}; const value = card.valueStyle ??= {}; return html`<details class="style"><summary>Appearance</summary><div class="grid">${this.field("Background", style.background, v => { style.background = v; this.changed(); })}${this.field("Text color", style.foreground, v => { style.foreground = v; this.changed(); })}${this.field("Accent", style.accent, v => { style.accent = v; this.changed(); })}${this.select("Font", value.fontFamily ?? "sans", ["sans", "sans-bold", "mono", "serif"], v => { value.fontFamily = v as Style["fontFamily"]; this.changed(); })}${this.select("Font size", value.fontSize ?? "auto", ["auto", "small", "medium", "large", "xlarge"], v => { value.fontSize = v as Style["fontSize"]; this.changed(); })}</div></details>`; }

  private cardSettings(card: DisplayCard, rowIndex: number, cardIndex: number) {
    const cards = this.dashboard!.pages[this.pageIndex].rows[rowIndex].cards;
    const hints = { number: "Displays a numeric value with an optional unit and progress visualization.", text: "Displays text from an entity or the static text below.", status: "Maps a state entity to two readable labels.", clock: "Displays local time without using an entity." };
    return html`<section class="card-settings"><div class="card-head"><strong>${card.title || `Card ${cardIndex + 1}`}</strong>${this.menu(html`<button @click=${() => { cards.splice(cardIndex + 1, 0, structuredClone(card)); this.selected = { row: rowIndex, card: cardIndex + 1 }; this.changed(); }}>Duplicate</button><button class="danger" ?disabled=${cards.length === 1} @click=${() => { if (cards.length > 1) { cards.splice(cardIndex, 1); this.selected = undefined; this.changed(); } }}>Delete</button>`)}</div><div class="grid">${this.select("Type", card.type, ["number", "text", "clock", "status"], value => { Object.keys(card).forEach(key => delete (card as unknown as Record<string, unknown>)[key]); Object.assign(card, newCard(value as DisplayCard["type"])); this.changed(); })}${this.field("Title", card.title, value => { card.title = value; this.changed(); })}<p class="hint">${hints[card.type]}</p>${["number", "status", "text"].includes(card.type) ? this.entity(card) : nothing}${card.type === "number" ? html`${this.field("Unit", card.unit, value => { card.unit = value; this.changed(); })}${this.field("Minimum", card.minimum, value => { card.minimum = Number(value); this.changed(); }, "number")}${this.field("Maximum", card.maximum, value => { card.maximum = Number(value); this.changed(); }, "number")}${this.select("Progress", card.progress ?? "none", ["none", "bar", "ring"], value => { card.progress = value as DisplayCard["progress"]; this.changed(); })}` : nothing}${card.type === "text" ? this.field("Static text", card.text, value => { card.text = value; this.changed(); }) : nothing}${card.type === "status" ? html`${this.field("On text", card.onText, value => { card.onText = value; this.changed(); })}${this.field("Off text", card.offText, value => { card.offText = value; this.changed(); })}` : nothing}</div>${this.styleEditor(card)}</section>`;
  }

  private rowEditor(row: DisplayRow, rowIndex: number) {
    const page = this.dashboard!.pages[this.pageIndex];
    return html`<section class="row-panel"><div class="row-head"><div class="row-title"><strong>Row ${rowIndex + 1}</strong><small>${row.cards.length} ${row.cards.length === 1 ? "card" : "cards"}</small></div>${this.menu(html`<button @click=${() => { page.rows.splice(rowIndex + 1, 0, structuredClone(row)); this.changed(); }}>Duplicate</button><button class="danger" ?disabled=${page.rows.length === 1} @click=${() => { if (page.rows.length > 1) { page.rows.splice(rowIndex, 1); this.selected = undefined; this.changed(); } }}>Delete</button>`)}</div>${this.field("Row title", row.title, value => { row.title = value; this.changed(); })}<nav class="card-tabs" aria-label=${`Cards in row ${rowIndex + 1}`}>${row.cards.map((card, cardIndex) => html`<button class=${this.selected?.row === rowIndex && this.selected?.card === cardIndex ? "active" : ""} aria-pressed=${this.selected?.row === rowIndex && this.selected?.card === cardIndex} @click=${() => this.selected = { row: rowIndex, card: cardIndex }}>Card ${cardIndex + 1} · ${card.type}</button>`)}</nav>${this.selected?.row === rowIndex ? this.cardSettings(row.cards[this.selected.card], rowIndex, this.selected.card) : nothing}${row.cards.length < 3 ? html`<button class="add" @click=${() => { row.cards.push(newCard()); this.selected = { row: rowIndex, card: row.cards.length - 1 }; this.changed(); }}>Add card</button>` : nothing}</section>`;
  }

  render() {
    const page = this.dashboard?.pages[this.pageIndex];
    return html`<main class="editor"><div class="topbar"><label>Display<select .value=${this.config.config_entry_id} @change=${(event: Event) => this.selectDisplay((event.target as HTMLSelectElement).value)}><option value="">Select display</option>${this.displays.map(display => html`<option value=${display.config_entry_id}>${display.title}${display.available ? "" : " (offline)"}</option>`)}</select></label><div class="sync ${this.syncState}" role="status" aria-live="polite"><i></i><span>${this.syncMessage}</span></div></div>${page ? html`<nav class="tabs" aria-label="Dashboard pages">${this.dashboard!.pages.map((item, index) => html`<button class=${index === this.pageIndex ? "active" : ""} @click=${() => void this.showPage(index)}>${item.title || item.id}</button>`)}<button @click=${() => { this.dashboard!.pages.push(newPage(this.dashboard!.pages.length + 1)); this.pageIndex = this.dashboard!.pages.length - 1; this.selected = { row: 0, card: 0 }; this.changed(); }}>Add page</button></nav><details class="page-settings"><summary>Page settings</summary><div class="grid">${this.field("Page ID", page.id, value => { page.id = value; this.changed(); })}${this.field("Title", page.title, value => { page.title = value; this.changed(); })}${this.field("Duration in seconds", page.durationSeconds, value => { page.durationSeconds = Number(value); this.changed(); }, "number")}${this.checkbox("Show title", page.showTitle !== false, value => { page.showTitle = value; this.changed(); })}</div></details><div class="rows">${page.rows.map((row, index) => this.rowEditor(row, index))}</div>${page.rows.length < 6 ? html`<button class="add" @click=${() => { page.rows.push(newRow()); this.changed(); }}>Add row</button>` : nothing}` : nothing}</main>`;
  }
}
