[platformio]
default_envs = sdpro

[env:sdpro]
platform = espressif8266@4.2.1
board = esp12e
framework = arduino
lib_deps =
  bodmer/TFT_eSPI@^2.5.43
  bblanchon/ArduinoJson@^6.21.5
board_build.flash_mode = dio
board_build.f_flash = 40000000L
board_build.ldscript = eagle.flash.4m2m.ld
monitor_speed = 115200
build_flags =
  -D PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY
  -D USER_SETUP_LOADED=1
  -D ST7789_DRIVER=1
  -D TFT_WIDTH=240
  -D TFT_HEIGHT=240
  -D TFT_MOSI=13
  -D TFT_SCLK=14
  -D TFT_CS=-1
  -D TFT_DC=0
  -D TFT_RST=2
  -D TFT_BL=5
  -D TOUCH_CS=-1
  -D TFT_BACKLIGHT_ON=LOW
  -D LOAD_GLCD=1
  -D LOAD_FONT2=1
  -D LOAD_FONT4=1
  -D LOAD_GFXFF=1
  -D SPI_FREQUENCY=40000000
  -D TFT_RGB_ORDER=TFT_BGR
  -D TFT_INVERSION_ON=1
